# Generated by spaday.cem from components.cem.json — do not edit by hand.
from __future__ import annotations

from typing import Any

from spaday.component import Child, Component

__all__ = ["PerspectivePanel"]


class PerspectivePanel(Component):
    """Perspective workspace whose data connection and layout are configured by a serializable prop."""

    tag = "perspective-panel"

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        config: Any = None,
        theme: str | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "config": config,
                "theme": theme,
            },
            **props,
        )
